#!/usr/bin/env python3
"""Reference digest — Stage 3 of the reference-intelligence pipeline.

Turns the machine-readable corpus + synthesis JSON into a human-readable Markdown
digest at docs/reference_synthesis_<node>.md, so the insights are actually
readable and — crucially — the GAP WISHLIST stays visible and promoted across
sessions instead of dying in a JSON blob. `/start` + the session handoff point
here; see memory project_reference_page_design.

Run:  python3 reference_digest.py [submariner speedmaster]   (no API key needed)
Also run as Stage 3 of .github/workflows/reference-synthesis.yml.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

PUBLIC = Path("public")
DOCS = Path("docs")


def _scope(x: dict) -> str:
    t = x.get("applies_to")
    return f"  ·  _scope: {', '.join(t)}_" if t else ""


def digest(node: str) -> None:
    syn_path = PUBLIC / f"reference_synthesis_{node}.json"
    corpus_path = PUBLIC / f"reference_corpus_{node}.json"
    if not syn_path.exists():
        print(f"[skip {node}: {syn_path} missing — run reference_synthesis.py first]")
        return
    syn = json.loads(syn_path.read_text())
    corpus = json.loads(corpus_path.read_text()) if corpus_path.exists() else {}

    o = []
    w = o.append
    w(f"# Reference synthesis — {node.title()}\n")
    w("_Auto-generated by `reference_digest.py` from the scrape + Opus 4.7 synthesis. "
      "Human-review surface: correct anything wrong before it feeds a page. "
      "**The Gaps & wishlist section is the backlog — it drives the next source scan.**_\n")

    # ── sources / word counts ──
    rows = sorted(((m.get("word_count", 0), m.get("publication", "?"), m.get("origin", ""), u)
                   for u, m in corpus.items() if isinstance(m, dict)), reverse=True)
    total = sum(r[0] for r in rows)
    w(f"\n## Sources scraped ({len(rows)} · {total:,} words)\n")
    w("| Words | Origin | Publication | URL |")
    w("|---:|---|---|---|")
    for words, pub, origin, url in rows:
        w(f"| {words:,} | {origin} | {pub} | {url} |")

    w("\n## Model context\n")
    w(syn.get("model_context", ""))

    w(f"\n## Consensus facts ({len(syn.get('consensus', []))})\n")
    for c in syn.get("consensus", []):
        srcs = " · ".join(f"[{i+1}]({s})" for i, s in enumerate(c.get("sources", [])))
        w(f"- **[{c.get('confidence')}]** {c.get('claim')}  \n  {srcs}{_scope(c)}")

    w(f"\n## Marks ({len(syn.get('marks', []))})\n")
    for m in syn.get("marks", []):
        srcs = " · ".join(f"[{i+1}]({s})" for i, s in enumerate(m.get("sources", [])))
        w(f"- **{m.get('name')}** — {m.get('explanation')}  \n  {srcs}{_scope(m)}")

    w(f"\n## Agreements & conflicts ({len(syn.get('conflicts', []))})\n")
    for c in syn.get("conflicts", []):
        w(f"- **{c.get('topic')}** — {c.get('note')}{_scope(c)}")
        for p in c.get("positions", []):
            w(f"  - {p}")

    w(f"\n## Stories worth telling ({len(syn.get('stories', []))})\n")
    for s in syn.get("stories", []):
        w(f"- **{s.get('title')}** — {s.get('why')}  \n  [source]({s.get('source')}){_scope(s)}")

    w(f"\n## Module candidates — future nodes ({len(syn.get('module_candidates', []))})\n")
    for m in syn.get("module_candidates", []):
        w(f"- **{m.get('module')}** — {m.get('rationale')}")

    w(f"\n## ⭐ Gaps & wishlist — drives the next scan ({len(syn.get('gaps', []))})\n")
    for g in syn.get("gaps", []):
        w(f"- **Gap:** {g.get('gap')}  \n  **→** {g.get('suggestion')}")

    DOCS.mkdir(exist_ok=True)
    out = DOCS / f"reference_synthesis_{node}.md"
    out.write_text("\n".join(o) + "\n")
    print(f"wrote {out} ({len(rows)} sources, {len(syn.get('gaps', []))} gaps)")


if __name__ == "__main__":
    for n in sys.argv[1:] or ["submariner", "speedmaster"]:
        digest(n)
